version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql
    command: '--explicit_defaults_for_timestamp'
    volumes:
      - ~/DB/${APP_NAME}/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  # キャッシュ用
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

#  今回は未使用のためコメントアウト
#  server:
#    image: golang:1.17
#    container_name: ${APP_NAME}-golang
#    command: go run /opt/server/main.go
#    volumes:
#      - .:/opt/server
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql
