version: '3'

services:
  master:
    image: locustio/locust:1.5.3
    ports:
     - "8089:8089"
    volumes:
      - ../:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master
    network_mode: host

  worker:
    image: locustio/locust
    volumes:
      - ../:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker
    network_mode: host